// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1wf2z4bB0P_QVBguxOY7DWz-kRNRJxZk',
    appId: '1:151454045801:web:2fa28569fd80bdd095f4f8',
    messagingSenderId: '151454045801',
    projectId: 'fooddeliveryproject-38123',
    authDomain: 'fooddeliveryproject-38123.firebaseapp.com',
    storageBucket: 'fooddeliveryproject-38123.firebasestorage.app',
    measurementId: 'G-TV8RKH740D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAe8Rvpl2swfs94mPwzplkZOS32GnbKAc',
    appId: '1:151454045801:android:df015b7f82d41a7795f4f8',
    messagingSenderId: '151454045801',
    projectId: 'fooddeliveryproject-38123',
    storageBucket: 'fooddeliveryproject-38123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRqex9BC67IePs1qWkJrb8n2_aZ8VASk',
    appId: '1:151454045801:ios:147de97e9b66d4e295f4f8',
    messagingSenderId: '151454045801',
    projectId: 'fooddeliveryproject-38123',
    storageBucket: 'fooddeliveryproject-38123.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRqex9BC67IePs1qWkJrb8n2_aZ8VASk',
    appId: '1:151454045801:ios:147de97e9b66d4e295f4f8',
    messagingSenderId: '151454045801',
    projectId: 'fooddeliveryproject-38123',
    storageBucket: 'fooddeliveryproject-38123.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1wf2z4bB0P_QVBguxOY7DWz-kRNRJxZk',
    appId: '1:151454045801:web:2fa28569fd80bdd095f4f8',
    messagingSenderId: '151454045801',
    projectId: 'fooddeliveryproject-38123',
    authDomain: 'fooddeliveryproject-38123.firebaseapp.com',
    storageBucket: 'fooddeliveryproject-38123.firebasestorage.app',
    measurementId: 'G-TV8RKH740D',
  );

}